import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it, vi } from "vitest";

vi.mock("next/font/google", () => ({
  Geist: () => ({ variable: "font-geist-sans" }),
  Geist_Mono: () => ({ variable: "font-geist-mono" }),
}));

import RootLayout, { metadata } from "./layout";

describe("RootLayout", () => {
  it("wraps children with the expected HTML shell and font classes", () => {
    const html = renderToStaticMarkup(
      <RootLayout>
        <div>app content</div>
      </RootLayout>,
    );

    expect(html).toContain('lang="en"');
    expect(html).toContain(
      'class="font-geist-sans font-geist-mono antialiased"',
    );
    expect(html).toContain("<div>app content</div>");
  });
});

describe("metadata", () => {
  it("describes the base app shell", () => {
    expect(metadata).toMatchObject({
      title: "Create Next App",
      description: "Generated by create next app",
    });
  });
});
